# Generated by Django 4.1.3 on 2022-11-19 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuoteApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoter', models.CharField(blank=True, max_length=225, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='quote',
            name='quoter',
        ),
        migrations.AddField(
            model_name='quote',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QuoteApp.actor'),
        ),
    ]
