# Generated by Django 4.1.3 on 2022-11-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuoteApp', '0002_actor_remove_quote_quoter_quote_actor'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=225)),
                ('city', models.CharField(max_length=225)),
                ('region', models.CharField(max_length=225)),
                ('country', models.CharField(max_length=225)),
            ],
        ),
    ]
