# Generated by Django 4.1.3 on 2022-11-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuoteApp', '0004_iplocation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iplocation',
            name='city',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='iplocation',
            name='country',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='iplocation',
            name='ip',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='iplocation',
            name='region',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
